version: '3.5'

services:
  # RabbitMQ
  ##########
  rabbitmq:
    image: rabbitmq:3.13.4-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      default:
        aliases:
          - rabbitmq
    ports:
      # AMPQ port
      - 127.0.0.1:${RABBITMQ_AMQP_PORT}:5672
      # Management port
      - 127.0.0.1:${RABBITMQ_MANAGEMENT_PORT}:15672
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking

volumes:
  # Rabbit-MQ
  rabbitmq-data:

networks:
  default:
    name: ${NETWORK}
    external: true
