services:
  # Postgres
  #######
  postgres:
    image: postgres:17
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - ./persistent-data/postgres:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres
    deploy:
      placement: 
        constraints: 
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - postgres_password

  # pgAdmin
  #########
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    volumes:
      - ./persistent-data/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - default
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    secrets:
      - pgadmin_password

networks:
  default:
    external: true
    name: ${NETWORK}

volumes:
  pgadmin_data:

secrets:
   postgres_password:
     file: ./docker-secrets/postgres_password.txt
   pgadmin_password:
     file: ./docker-secrets/pgadmin_password.txt
