version: '3.5'

services:
  
  # Redis
  #######
  redis:
    image: redis/redis-stack-server:7.4.0-v1
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT}:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    #command: redis-server --dir /data --save 60 1 --appendonly yes --requirepass redis123
    environment:
      REDIS_ARGS: "--dir /data --appendonly yes --save 60 1 --requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
    networks:
      default:
        aliases:
          - redis
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking

  # Redis insight
  ##########################
  redis-insight:
    image: redislabs/redisinsight:2.64
    ports:
      - target: 5540
        published: ${REDIS_INSIGHT_PORT}
        mode: host
    volumes:
      - redis-insight-data:/data
    environment:
      - RITRUSTEDORIGINS=${REDIS_INSIGHT_ORIGIN} # Trust the proxy origin
      - RIPROXYENABLE=t                        # Enable Subpath Proxy
      - RIPROXYPATH=${REDIS_INSIGHT_PATH}  # Set static proxy subpath
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      default:

    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking

volumes:
  # Redis
  redis-data:
  redis-insight-data:

networks:
  default:
    name: ${NETWORK}
    external: true
