services:
  # Postgres
  #######
  postgres:
    image: postgres:17
    restart: always
    shm_size: 128mb
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    deploy:
      placement: 
        constraints: 
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - postgres_password

networks:
  default:
    external: true
    name: ${NETWORK}

secrets:
   postgres_password:
     file: ./docker-secrets/postgres_password.txt
