version: '3.1'

services:

  # MySQL: phpMyAdmin
  ###################
  phpmyadmin:
    image: phpmyadmin:5.2.0
    ports:
    - "${PMA_PORT}:80"
    environment:
      PMA_PORT: 3306
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}

  # Log database explorer
  ##########################
  mongo-express:
    image: mongo-express
    ports:
      - ${ME_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:27017/
      ME_CONFIG_SITE_BASEURL: ${ME_CONFIG_SITE_BASEURL}
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK}
    external: true
