version: '3.5'

services:
  # MySQL
  #######
  mysql:
    platform: linux/x86_64
    image: mysql:8.1
    ports: 
      - ${MYSQL_PORT}:3306
    restart: unless-stopped
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      default:
        aliases:
          - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking

  # MongoDB
  #########
  mongodb:
    image: mongo:6.0.5
    volumes:
      - mongodb:/etc/mongo
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      default:
        aliases:
          - mongodb
    ports: 
      - 127.0.0.1:${MONGODB_PORT}:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking
  
  # Redis
  #######
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - redis-data:/data
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    restart: unless-stopped
    networks:
      default:
        aliases:
          - redis
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking

  # RabbitMQ
  ##########
  rabbitmq:
    image: rabbitmq:3.12.6-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      default:
        aliases:
          - rabbitmq
    ports:
      # AMPQ port
      - 127.0.0.1:${RABBITMQ_AMQP_PORT}:5672
      # Management port
      - 127.0.0.1:${RABBITMQ_MANAGEMENT_PORT}:15672
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking

volumes:
  # MySQL
  mysql-data:
  # MongoDB
  mongodb:
  mongodb-data:
  mongodb-config:
  # Redis
  redis-data:
  # Rabbit-MQ
  rabbitmq-data:

networks:
  default:
    name: ${NETWORK}
    external: true
