services:
  # Postgres
  #######
  postgres:
    image: postgres:17
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - ./persistent-data/postgres:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres
    deploy:
      placement: 
        constraints: 
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    secrets:
      - postgres_password


networks:
  default:
    external: true
    name: ${NETWORK}

secrets:
   postgres_password:
     file: ./docker-secrets/postgres_password.txt