version: '3.5'

services:
  # MySQL
  #######
  mysql:
    platform: linux/x86_64
    image: mysql:8.1
    ports: 
      - ${MYSQL_PORT}:3306
    restart: unless-stopped
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      default:
        aliases:
          - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  # MongoDB
  #########
  mongodb:
    image: mongo:6.0.5
    volumes:
      - mongodb:/etc/mongo
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      default:
        aliases:
          - mongodb

    ports: 
      - ${MONGODB_PORT}:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}


volumes:
  # MySQL
  mysql-data:
  # MongoDB
  mongodb:
  mongodb-data:
  mongodb-config:

networks:
  default:
    name: ${NETWORK}
    external: true
