version: '3.1'

services:

  # MySQL: phpMyAdmin
  ###################
  phpmyadmin:
    image: phpmyadmin:5.2.0
    ports:
    - "${PMA_PORT}:80"
    restart: unless-stopped
    environment:
      PMA_PORT: 3306
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}

  # Log database explorer
  ##########################
  # mongo-express:
  #   restart: unless-stopped
  #   image: mongo-express
  #   ports:
  #     - 8102:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${LOG_DB_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${LOG_DB_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${LOG_DB_USERNAME}:${LOG_DB_PASSWORD}@${LOG_DB_HOST}:${LOG_DB_PORT}/
  #     ME_CONFIG_SITE_BASEURL: ${LOG_DB_EXPLORER_SITE_BASEURL}

networks:
  default:
    name: main-network
    external: true
