version: '3.7'

services:
  portainer_agent:
    image: portainer/agent:2.19.1
    networks:
      - portainer_agent_network
    ports:
      - "${PORTAINER_AGENT_PORT}:9001/tcp"
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking

networks:
  portainer_agent_network:
    driver: overlay
