version: '3.5'

services:
  # MongoDB
  #########
  mongodb:
    image: mongo:6.0.5
    volumes:
      - mongodb:/etc/mongo
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      default:
        aliases:
          - mongodb
    ports: 
      - 127.0.0.1:${MONGODB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_root_password
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    deploy:
      placement: 
        constraints: 
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure

    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking

volumes:
  # MongoDB
  mongodb:
  mongodb-data:
  mongodb-config:

networks:
  default:
    external: true
    name: ${NETWORK}

secrets:
   mongodb_root_username:
     file: ./docker-secrets/mongodb_root_username.txt
   mongodb_root_password:
     file: ./docker-secrets/mongodb_root_password.txt