global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'server-cpu-a'
    static_configs:
      - targets: ['node-exporter:9100']

  # Another node exporter on another host
  - job_name: 'server-cpu-b'
    static_configs:
      - targets: ['host.com']
    metrics_path: "/metrics"
    basic_auth:
      username: ''
      password: ''

remote_write:
  - url: ""
    basic_auth:
       username: ""
       password: ""
